// ============================================================
// Lambdas
// ============================================================
// Lambdas are anonymous function objects (closures) defined inline.
// Each lambda has a unique, unnamed type generated by the compiler.

#include <iostream>
#include <vector>
#include <algorithm>
#include <functional>
#include <memory>

// ---- Capture modes ----------------------------------------------------------
// []       — capture nothing (pure function)
// [=]      — capture all locals by value
// [&]      — capture all locals by reference (careful: dangling refs!)
// [x]      — capture x by value
// [&x]     — capture x by reference
// [=, &x]  — all by value, but x by reference
// [this]   — capture this pointer (member access)
// [*this]  — capture the object by value (C++17)

void captureExamples() {
    int x = 10, y = 20;

    auto addXY = [x, y] { return x + y; };         // copy of x and y at creation
    auto addRef = [&x, &y] { return x + y; };       // references to x and y

    x = 99;
    std::cout << addXY() << "\n";   // 30 — captured old values
    std::cout << addRef() << "\n";  // 119 — sees updated x

    // Init capture (C++14): create a new variable in the capture
    auto ptr = std::make_unique<int>(42);
    auto owns = [p = std::move(ptr)] { return *p; };  // unique_ptr moved into lambda
    std::cout << owns() << "\n";   // 42
    // ptr is now null; `owns` owns the pointer

    // [*this] capture (C++17): safe even if the object is destroyed
    struct Foo {
        int val = 5;
        auto makeGetter() { return [*this] { return val; }; }
    };
    auto getter = Foo{}.makeGetter();   // Foo temporary destroyed; lambda has its own copy
    std::cout << getter() << "\n";   // 5
}

// ---- mutable lambdas --------------------------------------------------------
// By default, captured-by-value variables are const inside the lambda.
// `mutable` removes that restriction.

void mutableLambda() {
    int count = 0;
    auto counter = [count]() mutable {  // count is a copy, but mutable
        return ++count;   // modifies the lambda's own copy of count
    };
    std::cout << counter() << "\n";  // 1
    std::cout << counter() << "\n";  // 2
    std::cout << "original count=" << count << "\n";  // 0 — unchanged
}

// ---- Generic lambdas (C++14) ------------------------------------------------
// `auto` parameters make a lambda into a function template.

void genericLambdas() {
    auto identity = [](auto x) { return x; };
    std::cout << identity(42) << " " << identity("hello") << "\n";

    auto add = [](auto a, auto b) { return a + b; };
    std::cout << add(1, 2) << " " << add(1.5, 2.5) << "\n";

    // Constrained auto (C++20): use concept
    auto addIntegrals = [](std::integral auto a, std::integral auto b) { return a + b; };
    std::cout << addIntegrals(3, 4) << "\n";
}

// ---- Lambda as a function object --------------------------------------------
// The compiler generates a struct with operator() for each lambda.
// Two lambdas with the same body are DIFFERENT types.

void lambdaType() {
    auto f = [](int x) { return x * 2; };
    auto g = [](int x) { return x * 2; };
    // decltype(f) != decltype(g) even though they look identical

    // std::function erases the type (at a runtime cost)
    std::function<int(int)> fn = f;
    std::cout << fn(5) << "\n";  // 10

    // Prefer templates or auto over std::function for hot paths
    auto apply = [](auto fn, int x) { return fn(x); };
    std::cout << apply(f, 5) << "\n";  // monomorphized: no type erasure
}

// ---- Immediately invoked lambda (IIFE) --------------------------------------
// Useful for complex initialization that requires statements, not just expressions.

void iifeExample() {
    const int result = [&] {
        int val = 0;
        for (int i = 1; i <= 10; ++i) val += i;
        return val;
    }();  // called immediately
    std::cout << "sum 1-10=" << result << "\n";  // 55
}

// ---- Recursive lambda -------------------------------------------------------
// A lambda cannot refer to itself by name normally.
// Solutions: std::function (overhead) or explicit Y-combinator / deduction guide.

void recursiveLambda() {
    // Using std::function: simple but has overhead
    std::function<int(int)> fib = [&fib](int n) -> int {
        return n <= 1 ? n : fib(n-1) + fib(n-2);
    };
    std::cout << "fib(10)=" << fib(10) << "\n";  // 55

    // Zero-overhead recursive lambda using a self-passing trick (C++23 deducing this)
    // or the classic Y-combinator pattern:
    auto factorial = [](auto self, int n) -> int {
        return n <= 1 ? 1 : n * self(self, n-1);
    };
    std::cout << "10!=" << factorial(factorial, 10) << "\n";  // 3628800
}

// ---- Lambda in algorithms ---------------------------------------------------

void lambdaInAlgorithms() {
    std::vector<int> v = {5, 3, 8, 1, 9, 2};

    std::sort(v.begin(), v.end(), [](int a, int b) { return a > b; });
    std::cout << "sorted desc: "; for (int x : v) std::cout << x << " "; std::cout << "\n";

    // Stateful lambda: count comparisons
    int comparisons = 0;
    std::sort(v.begin(), v.end(), [&comparisons](int a, int b) {
        ++comparisons;
        return a < b;
    });
    std::cout << "comparisons=" << comparisons << "\n";
}

int main() {
    std::cout << "=== capture ===\n";          captureExamples();
    std::cout << "=== mutable ===\n";          mutableLambda();
    std::cout << "=== generic ===\n";          genericLambdas();
    std::cout << "=== type erasure ===\n";     lambdaType();
    std::cout << "=== IIFE ===\n";             iifeExample();
    std::cout << "=== recursive ===\n";        recursiveLambda();
    std::cout << "=== in algorithms ===\n";    lambdaInAlgorithms();
}
